### ISSUE TITLE
Problemas de visualización en el pdf exportado 

### ISSUE THREAD

**Issue by aitorjus** [mikel-egana-aranguren/EHU-GP-01#2]
En la diapositiva 22 no se ve **la fórmula del cálculo de duración de cada actividad**
![diapositiva_22](https://user-images.githubusercontent.com/44173184/109555283-a2082e80-7ad5-11eb-8ab8-e66481efda16.png)
En la diapositiva 29 no se visualiza **la fórmula de la holgura libre**
![diapositiva_29](https://user-images.githubusercontent.com/44173184/109555282-a0d70180-7ad5-11eb-92e4-82240fa04c11.png)
En la diapositiva 30 no se visualiza **la fórmula de la holgura total**
![diapositiva_30](https://user-images.githubusercontent.com/44173184/109555279-9f0d3e00-7ad5-11eb-8d6a-c510f5a976a8.png)
Petición de mejora de visualización en la diapositiva 34, que **la imagen del grafo vaya después de la tabla y no debajo**
![diapositiva_34](https://user-images.githubusercontent.com/44173184/109556487-2effb780-7ad7-11eb-955f-e4b3fb24d392.png)

**Comment by mikel-egana-aranguren** [comment]
Gracias. 

La solucion es descargar el codigo (Code; Download ZIP) y abrir el index.html. Salen todas las ecuaciones y dibujos.
